import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { CalendarClock, Check, ChevronDown, ExternalLink } from "lucide-react";
import { supabaseServer } from "@/lib/supabase/server";
import { getCurrentRole, getDailyStats, getDatasetSnapshots, getPipelineByKey, getPipelineManualRuns, getPipelineScheduleAudit, getRecentRuns, getRunStages } from "@/lib/data";
import { changedRows, processedRows, rejectedRows, runMode } from "@/lib/run-stats";
import { describeCron } from "@/lib/schedule";
import { formatDuration, formatNumber, formatRelative, formatUtc } from "@/lib/format";
import { HealthBadge, RunStatusBadge } from "@/components/StatusBadge";
import { ManualRunButton } from "@/components/ManualRunButton";
import { ReferenceVolumeChart } from "@/components/ReferenceVolumeChart";
import { EmptyState } from "@/components/EmptyState";
import { isLocalDashboardPreview } from "@/lib/local-preview";

export const dynamic = "force-dynamic";
const tabs = ["overview","runs","quality","configuration","audit"] as const;
const good = new Set(["succeeded","succeeded_with_warnings","unchanged"]);

export default async function PipelineDetail({ params, searchParams }: { params:Promise<{key:string}>; searchParams:Promise<{tab?:string}> }) {
  const [{key},query] = await Promise.all([params,searchParams]); const sb=await supabaseServer(); const {data}=await sb.auth.getUser(); if(!data.user&&!isLocalDashboardPreview()) redirect("/login"); const p=await getPipelineByKey(key); if(!p) notFound(); const tab=tabs.includes(query.tab as typeof tabs[number])?query.tab!:"overview";
  const [role,runs,daily,snapshots,manual,scheduleAudit]=await Promise.all([getCurrentRole(),getRecentRuns({pipelineKey:key,limit:100}),getDailyStats(p.id,30),getDatasetSnapshots(p.id,50),getPipelineManualRuns(p.id),getPipelineScheduleAudit(p.id)]); const latest=runs[0]; const stages=latest?await getRunStages(latest.id):[]; const ok=runs.filter((r)=>good.has(r.status)).length; const rate=runs.length?Math.round(ok/runs.length*1000)/10:null; const durations=runs.map((r)=>r.duration_s).filter((value):value is number=>value!=null).sort((a,b)=>a-b); const median=durations.length?durations[Math.floor(durations.length/2)]:null; const canRun=role==="operator"||role==="admin";
  const latestStats=latest?.stats??{}; const stat=(...keys:string[])=>{for(const k of keys){const v=latestStats[k];if(typeof v==="string"||typeof v==="number")return String(v)}return "—"};
  return <section>
    <div className="ref-crumb"><Link href="/pipelines">Pipelines</Link> &nbsp;/&nbsp; {p.source_key} &nbsp;/&nbsp; {p.name}</div>
    <div className="ref-page-head"><div><div className="ref-detail-title"><h1>{p.name}</h1><HealthBadge state={p.health_state}/></div><p>Owner · Data Platform &nbsp; | &nbsp; Repository · {p.repository?.replace("https://","")??"Not configured"}</p></div><div className="ref-actions"><ManualRunButton pipelineKey={p.key} canRun={canRun} scheduler={p.scheduler}/><Link href={`/pipelines/${p.key}?tab=configuration`} className="ref-btn"><CalendarClock className="size-3.5"/>Edit schedule</Link></div></div>
    <div className="ref-facts surface"><div className="ref-fact"><small>Last success</small><strong>{formatRelative(p.last_success_started_at)}</strong></div><div className="ref-fact"><small>Freshness</small><strong>{p.freshness_hours==null?"—":`${p.freshness_hours.toFixed(1)}h / ${p.freshness_sla_hours}h SLA`}</strong></div><div className="ref-fact"><small>Next run</small><strong>{describeCron(p.schedule_expression)}</strong></div><div className="ref-fact"><small>Success 30d</small><strong>{rate==null?"—":`${rate}%`}</strong></div><div className="ref-fact"><small>Median duration</small><strong>{formatDuration(median)}</strong></div></div>
    <nav className="ref-tabs">{tabs.map((item)=><Link key={item} href={`/pipelines/${p.key}?tab=${item}`} className={tab===item?"active":""}>{item==="quality"?"Data quality":item==="audit"?"Audit log":item}</Link>)}</nav>

    {tab==="overview"&&<div className="ref-grid-detail"><div><div className="surface mb-[14px] overflow-hidden"><div className="ref-card-head"><h2>Freshness &amp; volume</h2><span className="ml-auto inline-flex items-center gap-1 text-[11px] text-wolfie-muted">Last 14 days<ChevronDown className="size-3"/></span></div><ReferenceVolumeChart data={daily.slice(-14)}/></div><div className="surface overflow-hidden"><div className="ref-card-head"><h2>Latest runs</h2><Link href={`/pipelines/${p.key}?tab=runs`}>View all runs</Link></div><div className="overflow-auto"><table className="data-table min-w-[660px]"><thead><tr><th>Started</th><th>Status</th><th>Duration</th><th>Rows</th><th>Lag at end</th><th>Triggered by</th></tr></thead><tbody>{runs.slice(0,4).map((r)=><tr key={r.id}><td><Link href={`/runs/${r.id}`}>{formatRelative(r.started_at)}</Link></td><td><RunStatusBadge status={r.status}/></td><td>{formatDuration(r.duration_s)}</td><td>{processedRows(r)==null?"—":formatNumber(processedRows(r)!)}</td><td>{p.freshness_hours==null?"—":`${p.freshness_hours.toFixed(0)}h`}</td><td className="capitalize">{r.trigger}</td></tr>)}</tbody></table></div></div></div><div><div className="surface mb-[14px] overflow-hidden"><div className="ref-card-head"><h2>Current sync</h2></div><div className="ref-sync-list"><div className="ref-sync-row"><span>Source watermark</span><b>{stat("source_watermark","max_source_ts","watermark")}</b></div><div className="ref-sync-row"><span>Destination watermark</span><b>{stat("destination_watermark","loaded_through")}</b></div><div className="ref-sync-row"><span>Mode</span><b className="text-state-healthy">{latest?runMode(latest):"—"}</b></div><div className="ref-sync-row"><span>Checkpoint</span><b>{stat("checkpoint","cursor","row_count")}</b></div></div></div><div className="surface overflow-hidden"><div className="ref-card-head"><h2>Stage performance</h2></div>{stages.length?<div className="ref-stage-list">{stages.map((stage)=><div className="ref-stage" key={stage.id}><span className="ref-stage-check"><Check className="size-3" strokeWidth={3}/></span><b>{stage.stage}</b><div className="h-[7px] overflow-hidden rounded-full bg-[#EDF0F3]"><i className="block h-full bg-state-healthy" style={{width:`${Math.min(100,Math.max(10,(stage.output_count??0)/(stage.input_count||1)*100))}%`}}/></div><span>{formatDuration(stage.finished_at?(new Date(stage.finished_at).getTime()-new Date(stage.started_at).getTime())/1000:null)}</span></div>)}</div>:<EmptyState compact title="Stage telemetry unavailable" description="No stage rows were reported for the latest run."/>}</div></div></div>}

    {tab==="runs"&&<div className="surface overflow-auto"><table className="data-table min-w-[900px]"><thead><tr><th>Started</th><th>Status</th><th>Duration</th><th>Processed</th><th>Changed</th><th>Rejected</th><th>Trigger</th><th>Commit</th></tr></thead><tbody>{runs.map((r)=><tr key={r.id}><td><Link href={`/runs/${r.id}`}>{formatUtc(r.started_at)}</Link></td><td><RunStatusBadge status={r.status}/></td><td>{formatDuration(r.duration_s)}</td><td>{processedRows(r)==null?"—":formatNumber(processedRows(r)!)}</td><td>{changedRows(r)==null?"—":formatNumber(changedRows(r)!)}</td><td>{rejectedRows(r)==null?"—":formatNumber(rejectedRows(r)!)}</td><td>{r.trigger}</td><td>{r.commit_sha?.slice(0,7)??"—"}</td></tr>)}</tbody></table></div>}

    {tab==="quality"&&<div className="surface overflow-hidden"><div className="ref-card-head"><h2>Dataset snapshots</h2></div>{snapshots.length?<div className="overflow-auto"><table className="data-table min-w-[850px]"><thead><tr><th>Dataset</th><th>Total rows</th><th>Inserted</th><th>Updated</th><th>Rejected</th><th>Duplicates</th><th>Snapshot</th></tr></thead><tbody>{snapshots.map((s)=><tr key={s.id}><td>{s.dataset}</td><td>{s.total_rows==null?"—":formatNumber(s.total_rows)}</td><td>{s.inserted_count??"—"}</td><td>{s.updated_count??"—"}</td><td>{s.rejected_count??"—"}</td><td>{s.duplicate_count??"—"}</td><td>{formatRelative(s.snapshot_at)}</td></tr>)}</tbody></table></div>:<EmptyState title="Quality telemetry unavailable" description="This pipeline has not published real dataset snapshots."/>}</div>}

    {tab==="configuration"&&<div className="ref-grid-even"><div className="surface overflow-hidden"><div className="ref-card-head"><h2>Schedule configuration</h2></div><div className="ref-summary-side">{[["Scheduler",p.scheduler],["Cron",p.schedule_expression??"Not scheduled"],["Timezone",p.schedule_timezone],["Strategy",p.refresh_strategy],["Freshness SLA",`${p.freshness_sla_hours}h`],["Expected duration",formatDuration(p.expected_duration_s)],["Timeout",formatDuration(p.timeout_s)]].map(([a,b])=><div className="ref-summary-line" key={a}><span>{a}</span><b>{b}</b></div>)}</div></div><div className="surface p-[15px]"><h2 className="text-sm font-bold">Destinations</h2><div className="mt-4 flex flex-wrap gap-2">{p.destination_tables.map((t)=><code className="rounded bg-wolfie-soft px-2 py-1 text-[11px]" key={t}>{t}</code>)}</div>{p.repository&&<a className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-wolfie-accent" href={p.repository} target="_blank" rel="noreferrer">Open repository<ExternalLink className="size-3"/></a>}</div></div>}

    {tab==="audit"&&<div className="surface overflow-hidden"><div className="ref-card-head"><h2>Audit log</h2></div>{manual.length||scheduleAudit.length?<div>{manual.map((m)=><div className="ref-summary-line px-[14px]" key={`m${m.id}`}><span>Manual {m.mode} run · {m.dispatch_status}</span><b>{formatUtc(m.requested_at)}</b></div>)}{scheduleAudit.map((a)=><div className="ref-summary-line px-[14px]" key={`s${a.id}`}><span>{a.action}</span><b>{formatUtc(a.created_at)}</b></div>)}</div>:<EmptyState title="No audit activity" description="No persisted manual-run or schedule audit records exist."/>}</div>}
  </section>;
}
