import Link from "next/link";
import { redirect } from "next/navigation";
import { AlarmClock, CircleAlert, Clock3, Settings2, TriangleAlert } from "lucide-react";
import { supabaseServer } from "@/lib/supabase/server";
import { getAlertEvents, getAlertRules, getCurrentRole, getPipelineHealth } from "@/lib/data";
import { PageHeader } from "@/components/PageHeader";
import { MetricCard } from "@/components/MetricCard";
import { HealthBadge } from "@/components/StatusBadge";
import { ConfirmAcknowledgeButton } from "@/components/ConfirmAcknowledgeButton";
import { EmptyState } from "@/components/EmptyState";
import { formatDuration, formatRelative, formatUtc } from "@/lib/format";
import { isLocalDashboardPreview } from "@/lib/local-preview";
import { ResolveIncidentButton } from "@/components/ResolveIncidentButton";
import { CsvExportButton } from "@/components/CsvExportButton";

export const dynamic="force-dynamic";
const mean=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
export default async function IncidentsPage({searchParams}:{searchParams:Promise<{incident?:string}>}){const sb=await supabaseServer();const {data}=await sb.auth.getUser();if(!data.user&&!isLocalDashboardPreview())redirect("/login");const [params,events,rules,pipelines,role]=await Promise.all([searchParams,getAlertEvents(),getAlertRules(),getPipelineHealth(),getCurrentRole()]);const unresolved=events.filter((e)=>e.status!=="resolved"&&e.status!=="expired");const requestedId=Number(params.incident);const selected=unresolved.find((event)=>event.id===requestedId)??unresolved[0];const pipelineById=new Map(pipelines.map((p)=>[p.id,p]));const selectedPipeline=selected?.pipeline_id?pipelineById.get(selected.pipeline_id):null;const ackTimes=events.filter((e)=>e.acknowledged_at).map((e)=>(new Date(e.acknowledged_at!).getTime()-new Date(e.fired_at).getTime())/1000);const resolveTimes=events.filter((e)=>e.resolved_at).map((e)=>(new Date(e.resolved_at!).getTime()-new Date(e.fired_at).getTime())/1000);const canAck=role==="operator"||role==="admin";
return <section><PageHeader title="Incidents" description="Operational exceptions requiring attention" actions={<Link href="#alert-rules" className="ref-btn ref-btn-primary"><Settings2 />Alert rules</Link>}/><div className="ref-metrics"><MetricCard label="Critical" value={unresolved.filter((e)=>e.severity==="critical").length} hint="Open now" tone="failed" icon={<CircleAlert className="size-4"/>}/><MetricCard label="Warning" value={unresolved.filter((e)=>e.severity==="warning").length} hint="Open now" tone="warning" icon={<TriangleAlert className="size-4"/>}/><MetricCard label="Mean time to acknowledge" value={mean(ackTimes)==null?"—":formatDuration(mean(ackTimes))} hint="Retained events" tone="running" icon={<AlarmClock className="size-4"/>}/><MetricCard label="Mean time to resolve" value={mean(resolveTimes)==null?"—":formatDuration(mean(resolveTimes))} hint="Retained events" tone="running" icon={<Clock3 className="size-4"/>}/></div>
<div className="ref-incident-layout"><div className="ref-incident-list surface"><div className="ref-card-head"><h2>Open incidents</h2></div>{unresolved.length?unresolved.map((e)=><Link href={`/alerts?incident=${e.id}`} scroll={false} className={`ref-incident-item ${selected?.id===e.id?"selected":""}`} key={e.id}><span className="ref-alert-icon" style={{background:e.severity==="critical"?"#e43d3d":"#e88908"}}><CircleAlert className="size-3.5"/></span><div><strong>{e.title}</strong><small className="capitalize">{e.severity} · {e.status} · {formatRelative(e.fired_at)}</small></div></Link>):<EmptyState compact title="No open incidents" description="The live alert-event table has no unresolved records."/>}</div>
<div className="ref-incident-body surface">{selected?<><div className="ref-incident-top"><span className="ref-alert-icon"><CircleAlert className="size-3.5"/></span><div><h2>{selected.title}</h2><div className="mt-2 flex gap-2"><span className={`status ${selected.severity}`}>{selected.severity}</span>{selectedPipeline&&<HealthBadge state={selectedPipeline.health_state}/>}</div></div><div className="ref-incident-actions">{selected.status==="open"&&canAck&&<ConfirmAcknowledgeButton alertId={selected.id}/>} {canAck&&<ResolveIncidentButton alertId={selected.id}/>} {!canAck&&<Link href="/login" className="ref-btn">Operator sign-in</Link>}</div></div><div className="ref-incident-grid"><div className="surface overflow-hidden"><div className="ref-card-head"><h3>Timeline</h3></div><div className="p-3">{[[selected.fired_at,"Alert fired",selected.description??"Detection rule threshold reached"],...(selected.acknowledged_at?[[selected.acknowledged_at,"Acknowledged",`Assigned to ${selected.acknowledged_by??"operator"}`]]:[]),...(selected.resolved_at?[[selected.resolved_at,"Resolved","Incident marked resolved"]]:[])].map(([time,title,copy])=><div className="grid grid-cols-[20px_70px_1fr] gap-2 border-b border-wolfie-border py-[11px] text-[11px]" key={`${time}${title}`}><span className="ref-event-dot bg-state-running/10 text-state-running"><CircleAlert className="size-2.5"/></span><small>{formatUtc(time)}</small><div><b>{title}</b><br/><small className="text-wolfie-muted">{copy}</small></div></div>)}</div></div><div><div className="surface mb-3 overflow-hidden"><div className="ref-card-head"><h3>Impact</h3></div><div className="ref-summary-side"><div className="ref-summary-line"><span>Affected dataset</span><b>{selectedPipeline?.name??"Workspace"}</b></div><div className="ref-summary-line"><span>Freshness lag</span><b className="text-state-failed">{selectedPipeline?.freshness_hours==null?"—":`${selectedPipeline.freshness_hours.toFixed(1)}h`}</b></div><div className="ref-summary-line"><span>Rule</span><b>{rules.find((r)=>r.id===selected.rule_id)?.name??"—"}</b></div></div></div><div className="surface overflow-hidden"><div className="ref-card-head"><h3>Evidence</h3></div><div className="ref-summary-side"><div className="ref-summary-line"><span>Latest failed run</span><b>{selected.run_id?`run_${selected.run_id}`:"—"}</b></div><div className="ref-summary-line"><span>Fired</span><b>{formatUtc(selected.fired_at)}</b></div></div></div></div></div></>:<EmptyState title="Incident queue is clear" description="When a real alert event fires, its timeline, impact and evidence will appear here."/>}</div></div>
<div id="alert-rules" className="surface mt-[14px] overflow-hidden"><div className="ref-card-head"><h2>Alert rules</h2><CsvExportButton className="ml-auto h-8 border-0 bg-transparent shadow-none" filename="wolfie-alert-rules.csv" headers={["Name","Key","Type","Severity","Enabled","Cooldown minutes","Channels"]} rows={rules.map((rule)=>[rule.name,rule.key,rule.rule_type,rule.severity,rule.enabled,rule.cooldown_minutes,rule.channels.join(";")])}/></div>{rules.length?<div className="overflow-auto"><table className="data-table min-w-[760px]"><thead><tr><th>Rule</th><th>Type</th><th>Severity</th><th>Cooldown</th><th>Channels</th><th>Status</th></tr></thead><tbody>{rules.map((rule)=><tr key={rule.id}><td className="name"><strong>{rule.name}</strong><small>{rule.key}</small></td><td className="capitalize">{rule.rule_type.replaceAll("_"," ")}</td><td><span className={`status ${rule.severity}`}>{rule.severity}</span></td><td>{rule.cooldown_minutes}m</td><td>{rule.channels.length?rule.channels.join(", "):"—"}</td><td><span className={`status ${rule.enabled?"success":"disabled"}`}>{rule.enabled?"Enabled":"Disabled"}</span></td></tr>)}</tbody></table></div>:<EmptyState compact title="No alert rules configured" description="The production alert-rule table returned no records."/>}</div></section>}
