import Link from "next/link";
import { redirect } from "next/navigation";
import { Settings } from "lucide-react";
import { supabaseServer } from "@/lib/supabase/server";
import { getAlertEvents, getAlertRules, getCurrentRole, getPipelineHealth } from "@/lib/data";
import { PageHeader } from "@/components/PageHeader";
import { MetricCard } from "@/components/MetricCard";
import { HealthBadge } from "@/components/StatusBadge";
import { ConfirmAcknowledgeButton } from "@/components/ConfirmAcknowledgeButton";
import { EmptyState } from "@/components/EmptyState";
import { formatDuration, formatRelative, formatUtc } from "@/lib/format";

export const dynamic="force-dynamic";
const mean=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
export default async function IncidentsPage(){const sb=await supabaseServer();const {data}=await sb.auth.getUser();if(!data.user)redirect("/login");const [events,rules,pipelines,role]=await Promise.all([getAlertEvents(),getAlertRules(),getPipelineHealth(),getCurrentRole()]);const unresolved=events.filter((e)=>e.status!=="resolved"&&e.status!=="expired");const selected=unresolved[0];const pipelineById=new Map(pipelines.map((p)=>[p.id,p]));const selectedPipeline=selected?.pipeline_id?pipelineById.get(selected.pipeline_id):null;const ackTimes=events.filter((e)=>e.acknowledged_at).map((e)=>(new Date(e.acknowledged_at!).getTime()-new Date(e.fired_at).getTime())/1000);const resolveTimes=events.filter((e)=>e.resolved_at).map((e)=>(new Date(e.resolved_at!).getTime()-new Date(e.fired_at).getTime())/1000);const canAck=role==="operator"||role==="admin";
return <section><PageHeader title="Incidents" description="Operational exceptions requiring attention" actions={<button disabled title="Alert-rule editing is not connected" className="ref-btn ref-btn-primary"><Settings className="size-3.5"/>Configure alerts</button>}/><div className="ref-metrics"><MetricCard label="Critical" value={unresolved.filter((e)=>e.severity==="critical").length} hint="Open now" tone="failed"/><MetricCard label="Warning" value={unresolved.filter((e)=>e.severity==="warning").length} hint="Open now" tone="warning"/><MetricCard label="Mean time to acknowledge" value={mean(ackTimes)==null?"—":formatDuration(mean(ackTimes))} hint="Retained events" tone="running"/><MetricCard label="Mean time to resolve" value={mean(resolveTimes)==null?"—":formatDuration(mean(resolveTimes))} hint="Retained events" tone="running"/></div>
<div className="ref-incident-layout"><div className="ref-incident-list surface"><div className="ref-card-head"><h2>Open incidents</h2></div>{unresolved.length?unresolved.map((e,index)=><div className={`ref-incident-item ${index===0?"selected":""}`} key={e.id}><span className="ref-alert-icon" style={{background:e.severity==="critical"?"#e43d3d":"#e88908"}}>!</span><div><strong>{e.title}</strong><small className="capitalize">{e.severity} · {e.status} · {formatRelative(e.fired_at)}</small></div></div>):<EmptyState compact title="No open incidents" description="The live alert-event table has no unresolved records."/>}</div>
<div className="ref-incident-body surface">{selected?<><div className="ref-incident-top"><span className="ref-alert-icon">!</span><div><h2>{selected.title}</h2><div className="mt-2 flex gap-2"><span className={`status ${selected.severity}`}>{selected.severity}</span>{selectedPipeline&&<HealthBadge state={selectedPipeline.health_state}/>}</div></div><div className="ref-incident-actions">{selected.status==="open"&&canAck&&<ConfirmAcknowledgeButton alertId={selected.id}/>}<button className="ref-btn">Assign</button><button className="ref-btn">Resolve</button></div></div><div className="ref-incident-grid"><div className="surface overflow-hidden"><div className="ref-card-head"><h3>Timeline</h3></div><div className="p-3">{[[selected.fired_at,"Alert fired",selected.description??"Detection rule threshold reached"],...(selected.acknowledged_at?[[selected.acknowledged_at,"Acknowledged",`Assigned to ${selected.acknowledged_by??"operator"}`]]:[]),...(selected.resolved_at?[[selected.resolved_at,"Resolved","Incident marked resolved"]]:[])].map(([time,title,copy])=><div className="grid grid-cols-[20px_70px_1fr] gap-2 border-b border-wolfie-border py-[11px] text-[11px]" key={`${time}${title}`}><span className="ref-event-dot bg-state-running/10 text-state-running">!</span><small>{formatUtc(time)}</small><div><b>{title}</b><br/><small className="text-wolfie-muted">{copy}</small></div></div>)}</div></div><div><div className="surface mb-3 overflow-hidden"><div className="ref-card-head"><h3>Impact</h3></div><div className="ref-summary-side"><div className="ref-summary-line"><span>Affected dataset</span><b>{selectedPipeline?.name??"Workspace"}</b></div><div className="ref-summary-line"><span>Freshness lag</span><b className="text-state-failed">{selectedPipeline?.freshness_hours==null?"—":`${selectedPipeline.freshness_hours.toFixed(1)}h`}</b></div><div className="ref-summary-line"><span>Rule</span><b>{rules.find((r)=>r.id===selected.rule_id)?.name??"—"}</b></div></div></div><div className="surface overflow-hidden"><div className="ref-card-head"><h3>Evidence</h3></div><div className="ref-summary-side"><div className="ref-summary-line"><span>Latest failed run</span><b>{selected.run_id?`run_${selected.run_id}`:"—"}</b></div><div className="ref-summary-line"><span>Fired</span><b>{formatUtc(selected.fired_at)}</b></div></div></div></div></div></>:<EmptyState title="Incident queue is clear" description="When a real alert event fires, its timeline, impact and evidence will appear here."/>}</div></div></section>}
