import Link from "next/link";
import { redirect } from "next/navigation";
import { BellRing, CheckCircle2, Filter } from "lucide-react";
import { supabaseServer } from "@/lib/supabase/server";
import { getAlertEvents, getAlertRules, getCurrentRole, getPipelineHealth } from "@/lib/data";
import { PageHeader } from "@/components/PageHeader";
import { MetricCard } from "@/components/MetricCard";
import { ConfirmAcknowledgeButton } from "@/components/ConfirmAcknowledgeButton";
import { formatRelative, formatUtc } from "@/lib/format";

export const dynamic = "force-dynamic";
export default async function AlertsPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const sb = await supabaseServer(); const { data } = await sb.auth.getUser(); if (!data.user) redirect("/login"); const params = await searchParams; const status = ["open", "acknowledged", "resolved"].includes(params.status ?? "") ? params.status! : "open";
  const [events, allEvents, rules, pipelines, role] = await Promise.all([getAlertEvents(status), getAlertEvents(), getAlertRules(), getPipelineHealth(), getCurrentRole()]); const pipelineById = new Map(pipelines.map((p) => [p.id, p])); const canAck = role === "operator" || role === "admin";
  const open = allEvents.filter((e) => e.status === "open"); const critical = open.filter((e) => e.severity === "critical").length; const acknowledged = allEvents.filter((e) => e.status === "acknowledged").length;
  return <div className="space-y-4"><PageHeader eyebrow="Incident management" title="Incidents" description="Live alert events, ownership state and configured detection rules." actions={<form className="flex items-center gap-2"><Filter className="size-3.5 text-wolfie-muted"/><select name="status" defaultValue={status} className="control capitalize">{["open", "acknowledged", "resolved"].map((s) => <option key={s}>{s}</option>)}</select><button className="secondary-button">Apply</button></form>}/>
    <section className="metrics-strip grid grid-cols-2 gap-3 lg:grid-cols-4"><MetricCard label="Open incidents" value={open.length} tone={open.length ? "failed" : "healthy"}/><MetricCard label="Critical" value={critical} tone={critical ? "failed" : "default"}/><MetricCard label="Acknowledged" value={acknowledged} tone="running"/><MetricCard label="Active rules" value={`${rules.filter((r) => r.enabled).length}/${rules.length}`} hint="Enabled detection rules"/></section>
    <section className="surface overflow-hidden"><div className="card-header"><div className="min-w-0 flex-1"><h2 className="card-heading capitalize">{status} incident queue</h2><p className="card-copy">{events.length} matching event{events.length === 1 ? "" : "s"}</p></div></div>{events.length ? <div className="overflow-x-auto"><table className="data-table min-w-[900px]"><thead><tr><th className="text-left">Severity</th><th className="text-left">Incident</th><th className="text-left">Pipeline</th><th className="text-left">Fired</th><th className="text-left">Ownership</th><th className="text-right">Action</th></tr></thead><tbody>{events.map((e) => { const p = e.pipeline_id ? pipelineById.get(e.pipeline_id) : null; return <tr key={e.id}><td><span className={`rounded-full px-2 py-1 text-[10px] font-semibold capitalize ${e.severity === "critical" ? "bg-state-failed/10 text-state-failed" : e.severity === "warning" ? "bg-state-warning/10 text-state-warning" : "bg-state-running/10 text-state-running"}`}>{e.severity}</span></td><td><div className="font-semibold">{e.title}</div><div className="max-w-md truncate text-[10px] text-wolfie-muted">{e.description ?? "No additional description"}</div></td><td>{p ? <Link href={`/pipelines/${p.key}`} className="font-medium hover:text-wolfie-accent">{p.name}</Link> : "—"}</td><td className="whitespace-nowrap">{formatRelative(e.fired_at)}<div className="text-[10px] text-wolfie-muted">{formatUtc(e.fired_at)}</div></td><td className="text-[10px] text-wolfie-muted">{e.acknowledged_at ? `Acknowledged ${formatRelative(e.acknowledged_at)}` : "Unassigned"}</td><td className="text-right">{e.status === "open" && canAck ? <ConfirmAcknowledgeButton alertId={e.id}/> : "—"}</td></tr>; })}</tbody></table></div> : <div className="empty-panel"><div><CheckCircle2 className="mx-auto size-8 text-state-healthy"/><h3 className="mt-3 text-xs font-semibold">No {status} incidents</h3><p className="mt-1 text-[11px] text-wolfie-muted">The live event table has no records for this state.</p></div></div>}</section>
    <section className="surface overflow-hidden"><div className="card-header"><div><h2 className="card-heading">Detection rules</h2><p className="card-copy">Configured alert policies from the production registry</p></div></div>{rules.length ? <div className="overflow-x-auto"><table className="data-table min-w-[760px]"><thead><tr><th className="text-left">Rule</th><th className="text-left">Type</th><th className="text-left">Severity</th><th className="text-left">Scope</th><th className="text-right">Cooldown</th><th className="text-left">State</th></tr></thead><tbody>{rules.map((r) => { const p = r.pipeline_id ? pipelineById.get(r.pipeline_id) : null; return <tr key={r.id}><td className="font-semibold">{r.name}<div className="text-[10px] font-normal text-wolfie-muted">{r.key}</div></td><td className="capitalize">{r.rule_type.replaceAll("_", " ")}</td><td className="capitalize">{r.severity}</td><td>{p?.name ?? "All pipelines"}</td><td className="text-right tabular">{r.cooldown_minutes} min</td><td><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${r.enabled ? "bg-state-healthy/10 text-state-healthy" : "bg-wolfie-soft text-wolfie-muted"}`}>{r.enabled ? "Enabled" : "Disabled"}</span></td></tr>; })}</tbody></table></div> : <div className="empty-panel"><BellRing className="size-6 text-wolfie-muted"/></div>}</section>
  </div>;
}
