import Link from "next/link";
import { redirect } from "next/navigation";
import { Clock3 } from "lucide-react";
import { supabaseServer } from "@/lib/supabase/server";
import { getPipelineHealth } from "@/lib/data";
import { PageHeader } from "@/components/PageHeader";
import { MetricCard } from "@/components/MetricCard";
import { HealthBadge } from "@/components/StatusBadge";
import { describeCron } from "@/lib/schedule";
import { formatRelative } from "@/lib/format";
import { isLocalDashboardPreview } from "@/lib/local-preview";

export const dynamic="force-dynamic";
function cronTime(expression:string|null){const parts=expression?.split(/\s+/);if(!parts||parts.length!==5)return"—";const [m,h]=parts;return /^\d+$/.test(m)&&/^\d+$/.test(h)?`${h.padStart(2,"0")}:${m.padStart(2,"0")}`:m.startsWith("*/")?`Every ${m.slice(2)}m`:"Recurring";}
export default async function SchedulesPage(){const sb=await supabaseServer();const {data}=await sb.auth.getUser();if(!data.user&&!isLocalDashboardPreview())redirect("/login");const pipelines=await getPipelineHealth();const healthById=new Map(pipelines.map((p)=>[p.id,p]));const active=pipelines.filter((p)=>p.enabled&&p.schedule_expression);const paused=pipelines.filter((p)=>!p.enabled);const missed=pipelines.filter((p)=>["stale","failed","stuck"].includes(p.health_state));const calendar=active.slice(0,4);const days=["Time (GST)","Sun","Mon","Tue","Wed","Thu","Fri","Sat"];
return <section><PageHeader title="Schedules" description="Control when and how every pipeline refreshes" actions={<button disabled title="External schedulers are the source of truth" className="ref-btn ref-btn-primary">＋ Create schedule</button>}/><div className="ref-metrics"><MetricCard label="Active schedules" value={active.length} hint={`${pipelines.length} registered pipelines`} tone="healthy" icon="▣"/><MetricCard label="Next hour" value="—" hint="External schedulers own next-run time" tone="running" icon="◷"/><MetricCard label="Paused" value={paused.length} hint="No configured upcoming runs" tone={paused.length?"warning":"default"} icon="Ⅱ"/><MetricCard label="Missed runs" value={missed.length} hint="Requires attention" tone={missed.length?"failed":"healthy"} icon="!"/></div>
<div className="ref-grid-detail"><div className="surface overflow-auto"><div className="ref-card-head"><h2>Weekly timeline</h2><span className="ml-auto text-[11px]">Week · GST (UTC+4)</span></div><div className="ref-calendar">{days.map((d)=><div className="ref-cal-cell ref-cal-head" key={d}>{d}</div>)}{calendar.flatMap((p)=>[<div className="ref-cal-cell" key={`${p.id}t`}>{cronTime(p.schedule_expression)}</div>,...Array.from({length:7},(_,day)=><div className="ref-cal-cell" key={`${p.id}-${day}`}><Link href={`/pipelines/${p.key}?tab=configuration`} className="ref-job block">{p.name}<br/>{describeCron(p.schedule_expression)}</Link></div>)])}</div></div><div className="surface overflow-hidden"><div className="ref-card-head"><h2>Upcoming</h2><Link href="#registry">View all</Link></div><ul className="ref-activity">{active.slice(0,5).map((p)=><li key={p.id}><span className="ref-event-dot bg-state-healthy/10 text-state-healthy"><Clock3 className="size-2.5"/></span><div>{p.name}<small>{describeCron(p.schedule_expression)} · {p.schedule_timezone}</small></div><span>Configured</span></li>)}</ul></div></div>
{missed.length>0&&<div className="ref-health-banner surface mt-[14px]"><span className="ref-warn-link">△</span><strong>{missed.length} schedule{missed.length===1?"":"s"} missed the expected freshness window.</strong><Link href="/alerts" className="ref-btn ml-auto">View incident</Link></div>}
<div id="registry" className="surface mt-[14px] overflow-auto"><div className="ref-card-head"><h2>Schedule registry</h2><a>Export</a></div><table className="data-table min-w-[1050px]"><thead><tr><th>Pipeline</th><th>Strategy</th><th>Cron</th><th>Timezone</th><th>Next run</th><th>Last triggered</th><th>Concurrency</th><th>Status</th></tr></thead><tbody>{pipelines.map((p)=>{const h=healthById.get(p.id);return <tr key={p.id}><td><Link href={`/pipelines/${p.key}?tab=configuration`}><b>{p.name}</b></Link></td><td className="capitalize">{p.refresh_strategy.replaceAll("_"," ")}</td><td className="font-mono text-[10px]">{p.schedule_expression??"—"}</td><td>{p.schedule_timezone}</td><td>{p.schedule_expression?"External scheduler":"—"}</td><td>{formatRelative(h?.latest_started_at)}</td><td>{p.concurrency??1}</td><td>{h?<HealthBadge state={h.health_state}/>:"—"}</td></tr>})}</tbody></table></div></section>}
