"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, ChevronLeft, ChevronRight, Download, Search, X } from "lucide-react";
import type { Run } from "@/lib/types";
import { RunStatusBadge } from "@/components/StatusBadge";
import { changedRows, processedRows, runMode } from "@/lib/run-stats";
import { formatDuration, formatNumber, formatRelative } from "@/lib/format";
import { downloadCsv } from "@/components/CsvExportButton";

const PAGE_SIZE = 20;

export function RunExplorer({ runs, initialQuery = "", initialStatus = "all" }: { runs: Run[]; initialQuery?: string; initialStatus?: string }) {
  const [query, setQuery] = useState(initialQuery); const [pipeline, setPipeline] = useState("all"); const [status, setStatus] = useState(initialStatus); const [trigger, setTrigger] = useState("all");
  const [page, setPage] = useState(0);
  const pipelines = useMemo(() => [...new Set(runs.map((r) => r.pipeline_name ?? r.pipeline_key ?? "Unmapped"))].sort(), [runs]);
  const statuses = useMemo(() => [...new Set(runs.map((r) => r.status))].sort(), [runs]);
  const triggers = useMemo(() => [...new Set(runs.map((r) => r.trigger))].sort(), [runs]);
  const filtered = useMemo(() => runs.filter((r) => { const needle = query.trim().toLowerCase(); const pipelineName = r.pipeline_name ?? r.pipeline_key ?? "Unmapped"; return (pipeline === "all" || pipelineName === pipeline) && (status === "all" || r.status === status) && (trigger === "all" || r.trigger === trigger) && (!needle || `${r.id} ${r.pipeline_name} ${r.pipeline_key} ${r.source_key} ${r.commit_sha}`.toLowerCase().includes(needle)); }), [runs, query, pipeline, status, trigger]);
  const pageCount = Math.max(1, Math.ceil(filtered.length / PAGE_SIZE));
  const visible = filtered.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE);
  useEffect(() => setPage(0), [query, pipeline, status, trigger, runs]);
  const exportRuns = () => downloadCsv("wolfie-runs.csv", ["Run ID","Pipeline","Status","Trigger","Mode","Started","Duration seconds","Processed","Changed","Commit"], filtered.map((run) => [run.id,run.pipeline_name ?? run.pipeline_key,run.status,run.trigger,runMode(run),run.started_at,run.duration_s,processedRows(run),changedRows(run),run.commit_sha]));
  return <div><div className="ref-filterbar"><label className="relative"><Search className="pointer-events-none absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-wolfie-muted"/><input className="ref-field ref-search-field pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search runs"/></label><select aria-label="Filter by pipeline" className="ref-field min-w-40" value={pipeline} onChange={(e) => setPipeline(e.target.value)}><option value="all">All pipelines</option>{pipelines.map((item) => <option key={item} value={item}>{item}</option>)}</select><select aria-label="Filter by status" className="ref-field min-w-40 capitalize" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">Any status</option>{statuses.map((s) => <option key={s}>{s}</option>)}</select><select aria-label="Filter by trigger" className="ref-field min-w-36 capitalize" value={trigger} onChange={(e) => setTrigger(e.target.value)}><option value="all">All triggers</option>{triggers.map((s) => <option key={s}>{s}</option>)}</select>{(query || pipeline !== "all" || status !== "all" || trigger !== "all") && <button type="button" className="ref-btn" onClick={() => { setQuery(""); setPipeline("all"); setStatus("all"); setTrigger("all"); }}><X className="size-3.5"/>Clear</button>}<button type="button" className="ref-btn ml-auto" onClick={exportRuns}><Download/>Export {filtered.length}</button></div>
    <div className="surface overflow-hidden"><div className="overflow-x-auto"><table className="data-table min-w-[1080px]"><thead><tr><th>Run ID</th><th>Pipeline</th><th>Status</th><th>Trigger</th><th>Started</th><th>Duration</th><th>Processed</th><th>Changed</th><th>Commit</th></tr></thead><tbody>{visible.map((r) => <tr key={r.id}><td><Link href={`/runs/${r.id}`} className="group font-semibold hover:text-wolfie-accent">run_{r.id}<ArrowUpRight className="ml-1 inline size-3 opacity-0 group-hover:opacity-100"/></Link></td><td>{r.pipeline_name ?? r.pipeline_key ?? "Unmapped"}</td><td><RunStatusBadge status={r.status}/></td><td className="capitalize">{r.trigger}<div className="text-[10px] text-wolfie-muted">{runMode(r)}</div></td><td className="whitespace-nowrap">{formatRelative(r.started_at)}</td><td>{formatDuration(r.duration_s)}</td><td>{processedRows(r) == null ? "—" : formatNumber(processedRows(r)!)}</td><td>{changedRows(r) == null ? "—" : formatNumber(changedRows(r)!)}</td><td className="font-mono text-[10px]">{r.commit_sha?.slice(0, 7) ?? "—"}</td></tr>)}</tbody></table>{filtered.length === 0 && <div className="empty-panel min-h-40 text-xs text-wolfie-muted">No runs match these filters.</div>}</div>{filtered.length > 0 && <div className="flex items-center justify-between border-t border-wolfie-border p-3 text-[11px] text-wolfie-muted"><span>Showing {page * PAGE_SIZE + 1}–{Math.min((page + 1) * PAGE_SIZE, filtered.length)} of {filtered.length}</span><span className="flex items-center gap-1"><button type="button" className="grid size-7 place-items-center rounded border border-wolfie-border hover:bg-wolfie-soft disabled:opacity-35" disabled={page === 0} onClick={() => setPage((value) => Math.max(0, value - 1))} aria-label="Previous page"><ChevronLeft className="size-3.5"/></button><b className="px-2 text-state-healthy">{page + 1} / {pageCount}</b><button type="button" className="grid size-7 place-items-center rounded border border-wolfie-border hover:bg-wolfie-soft disabled:opacity-35" disabled={page >= pageCount - 1} onClick={() => setPage((value) => Math.min(pageCount - 1, value + 1))} aria-label="Next page"><ChevronRight className="size-3.5"/></button></span></div>}</div></div>;
}
