"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import { ArrowUpRight, Search, X } from "lucide-react";
import type { Run } from "@/lib/types";
import { RunStatusBadge } from "@/components/StatusBadge";
import { changedRows, processedRows, runMode } from "@/lib/run-stats";
import { formatDuration, formatNumber, formatRelative } from "@/lib/format";

export function RunExplorer({ runs, initialQuery = "", initialStatus = "all" }: { runs: Run[]; initialQuery?: string; initialStatus?: string }) {
  const [query, setQuery] = useState(initialQuery); const [status, setStatus] = useState(initialStatus); const [trigger, setTrigger] = useState("all");
  const statuses = useMemo(() => [...new Set(runs.map((r) => r.status))].sort(), [runs]);
  const triggers = useMemo(() => [...new Set(runs.map((r) => r.trigger))].sort(), [runs]);
  const filtered = useMemo(() => runs.filter((r) => { const needle = query.trim().toLowerCase(); return (status === "all" || r.status === status) && (trigger === "all" || r.trigger === trigger) && (!needle || `${r.id} ${r.pipeline_name} ${r.pipeline_key} ${r.source_key} ${r.commit_sha}`.toLowerCase().includes(needle)); }), [runs, query, status, trigger]);
  return <div className="space-y-3"><div className="surface flex flex-col gap-2 p-3 md:flex-row md:items-center"><label className="relative min-w-0 flex-1"><Search className="absolute left-3 top-1/2 size-3.5 -translate-y-1/2 text-wolfie-muted"/><input className="control w-full pl-9" value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search run, pipeline, source or commit…"/></label><select className="control min-w-40 capitalize" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">All statuses</option>{statuses.map((s) => <option key={s}>{s}</option>)}</select><select className="control min-w-36 capitalize" value={trigger} onChange={(e) => setTrigger(e.target.value)}><option value="all">All triggers</option>{triggers.map((s) => <option key={s}>{s}</option>)}</select>{(query || status !== "all" || trigger !== "all") && <button className="secondary-button" onClick={() => { setQuery(""); setStatus("all"); setTrigger("all"); }}><X className="size-3.5"/>Clear</button>}</div>
    <div className="table-shell overflow-x-auto"><table className="data-table min-w-[1080px]"><thead><tr><th className="text-left">Run</th><th className="text-left">Pipeline</th><th className="text-left">Status</th><th className="text-left">Mode / trigger</th><th className="text-left">Started</th><th className="text-right">Duration</th><th className="text-right">Processed</th><th className="text-right">Changed</th><th className="text-left">Commit</th></tr></thead><tbody>{filtered.map((r) => <tr key={r.id}><td><Link href={`/runs/${r.id}`} className="group font-semibold hover:text-wolfie-accent">#{r.id}<ArrowUpRight className="ml-1 inline size-3 opacity-0 group-hover:opacity-100"/></Link></td><td><div className="max-w-48 truncate font-medium">{r.pipeline_name ?? r.pipeline_key ?? "Unmapped"}</div><div className="text-[10px] text-wolfie-muted">{r.source_key ?? "—"}</div></td><td><RunStatusBadge status={r.status}/></td><td><div className="capitalize">{runMode(r)}</div><div className="text-[10px] capitalize text-wolfie-muted">{r.trigger}{r.attempt > 1 ? ` · attempt ${r.attempt}` : ""}</div></td><td className="whitespace-nowrap text-wolfie-muted">{formatRelative(r.started_at)}</td><td className="text-right tabular">{formatDuration(r.duration_s)}</td><td className="text-right tabular">{processedRows(r) == null ? "—" : formatNumber(processedRows(r)!)}</td><td className="text-right tabular">{changedRows(r) == null ? "—" : formatNumber(changedRows(r)!)}</td><td className="font-mono text-[10px] text-wolfie-muted">{r.commit_sha?.slice(0, 7) ?? "—"}</td></tr>)}</tbody></table>{filtered.length === 0 && <div className="empty-panel min-h-40 text-xs text-wolfie-muted">No runs match these filters.</div>}</div><div className="text-[10px] text-wolfie-muted">Showing {filtered.length} of {runs.length} retained production runs.</div></div>;
}
