import { redirect } from "next/navigation";
import { supabaseServer } from "@/lib/supabase/server";
import { getAllDatasetSnapshots, getPipelineHealth } from "@/lib/data";
import { PageHeader } from "@/components/PageHeader";
import { MetricCard } from "@/components/MetricCard";
import { EmptyState } from "@/components/EmptyState";
import { formatNumber, formatRelative } from "@/lib/format";
import { isLocalDashboardPreview } from "@/lib/local-preview";

export const dynamic="force-dynamic";
export default async function QualityPage(){const sb=await supabaseServer();const {data}=await sb.auth.getUser();if(!data.user&&!isLocalDashboardPreview())redirect("/login");const [pipelines,snapshots]=await Promise.all([getPipelineHealth(),getAllDatasetSnapshots()]);const pipelineById=new Map(pipelines.map((p)=>[p.id,p]));const latest=new Map<number,typeof snapshots[number]>();for(const s of snapshots)if(!latest.has(s.pipeline_id))latest.set(s.pipeline_id,s);const reported=[...latest.values()];const failed=reported.filter((s)=>(s.duplicate_count??0)>0||(s.rejected_count??0)>0);const schemaChanges=reported.filter((s)=>s.schema_version);const monitored=new Set(reported.map((s)=>s.pipeline_id));
return <section><PageHeader title="Data quality" description="Completeness, uniqueness and schema health across published datasets" actions={<><button className="ref-btn">▣ Last 7 days⌄</button><button className="ref-btn">All sources⌄</button></>}/><div className="ref-metrics"><MetricCard label="Passing checks" value={reported.length?reported.length-failed.length:"—"} hint="Latest real snapshots" tone="healthy" icon="◇"/><MetricCard label="Failed checks" value={failed.length} hint="Rows with duplicate/rejection signals" tone={failed.length?"failed":"default"} icon="!"/><MetricCard label="Datasets monitored" value={monitored.size} hint={`${pipelines.length} pipelines registered`} tone="running" icon="▤"/><MetricCard label="Schema changes" value={schemaChanges.length} hint="Snapshots reporting a schema version" tone={schemaChanges.length?"warning":"default"} icon="▱"/></div>
<div className="ref-quality-grid"><div className="surface overflow-hidden"><div className="ref-card-head"><h2>Quality score by dataset</h2></div>{reported.length?<div className="overflow-auto"><table className="data-table min-w-[680px]"><thead><tr><th>Dataset</th><th>Total rows</th><th>Distinct keys</th><th>Duplicates</th><th>Rejected</th><th>Snapshot</th></tr></thead><tbody>{reported.map((s)=><tr key={s.id}><td className="name"><strong>{s.dataset}</strong><small>{pipelineById.get(s.pipeline_id)?.name??`Pipeline ${s.pipeline_id}`}</small></td><td><span className="ref-heat">{s.total_rows==null?"—":formatNumber(s.total_rows)}</span></td><td>{s.distinct_business_keys==null?"—":formatNumber(s.distinct_business_keys)}</td><td><span className={`ref-heat ${(s.duplicate_count??0)>0?"warn":""}`}>{s.duplicate_count??"—"}</span></td><td><span className={`ref-heat ${(s.rejected_count??0)>0?"fail":""}`}>{s.rejected_count??"—"}</span></td><td>{formatRelative(s.snapshot_at)}</td></tr>)}</tbody></table></div>:<EmptyState title="Quality telemetry unavailable" description="The production snapshot table has no records, so no quality scores are fabricated."/>}</div><div className="surface overflow-hidden"><div className="ref-card-head"><h2>Issues requiring attention</h2><a>View all</a></div>{failed.length?<table className="data-table"><thead><tr><th>Issue</th><th>Dataset</th><th>Severity</th><th>Rows</th></tr></thead><tbody>{failed.map((s)=><tr key={s.id}><td>{(s.duplicate_count??0)>0?"Duplicate records":"Rejected rows"}</td><td>{s.dataset}</td><td><span className={`status ${(s.rejected_count??0)>0?"critical":"warning"}`}>{(s.rejected_count??0)>0?"Critical":"Warning"}</span></td><td>{formatNumber((s.duplicate_count??0)+(s.rejected_count??0))}</td></tr>)}</tbody></table>:<EmptyState title="No measured quality issues" description={reported.length?"Latest snapshots report no duplicates or rejected rows.":"No snapshots are available for evaluation."}/>}</div></div>
<div className="ref-grid-even mt-[14px]"><div className="surface overflow-hidden"><div className="ref-card-head"><h2>Quality trend</h2></div><EmptyState title="Trend unavailable" description="At least two real snapshots per dataset are required before a trend can be plotted."/></div><div className="surface overflow-hidden"><div className="ref-card-head"><h2>Recent schema changes</h2></div>{schemaChanges.length?<table className="data-table"><thead><tr><th>Dataset</th><th>Change</th><th>Details</th><th>Status</th></tr></thead><tbody>{schemaChanges.slice(0,5).map((s)=><tr key={s.id}><td>{s.dataset}</td><td><span className="ref-heat">Schema reported</span></td><td>{s.schema_version}</td><td><span className="status success">Observed</span></td></tr>)}</tbody></table>:<EmptyState title="No schema telemetry" description="No snapshot currently reports a schema version."/>}</div></div></section>}
